#!/usr/bin/env node
// Generator for src/blog/generated-posts.ts.
//
// Renders content/blog/*.md to a committed, auto-generated TypeScript module at
// build time, so the browser bundle never ships a Markdown parser. Mirrors
// scripts/build-eco-data.mjs. Drafts (frontmatter `draft: true`) are excluded.
//
// To regenerate: `npm run blog:gen` (also runs as the first step of `npm run build`).

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { readPublishedPosts } from './lib/posts.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'src', 'blog', 'generated-posts.ts');

// Drop the raw `markdown` field (only gen-seo needs it); JSON.stringify omits
// undefined-valued optional keys (updated, ogImage) automatically.
const posts = readPublishedPosts().map(({ markdown, ...rest }) => rest);

const out = `// Auto-generated by scripts/build-blog.mjs. Do not edit by hand.
// Source: content/blog/*.md — regenerate with \`npm run blog:gen\`.
import type { BlogPost } from './types';

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`;
writeFileSync(outPath, out);
console.log(`Wrote ${posts.length} blog post(s) to ${outPath}`);
